name: build_and_test

on: [push]

jobs:
  windows:
    runs-on: windows-2016
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Windows VS2017
      run: |
        cmake --version
        mkdir build
        cd build
        cmake ..
        dir
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && msbuild.exe flecs.sln /p:CL_MPCount=2
  mac:
    runs-on: macOS-10.14
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: macOS Xcode 10.2
      run: |
        cmake --version
        mkdir build
        cd build
        cmake ..
        ls -al
        make
