name: build_and_test

on: [push]

jobs:
  windows:
    runs-on: windows-2016
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Windows VS2017
      run: |
        cmake --version
        mkdir build64
        cd build64
        cmake -G "Visual Studio 15 2017 Win64" ..
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && msbuild.exe flecs.sln /p:Configuration=Debug /p:CL_MPCount=2
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && msbuild.exe flecs.sln /p:Configuration=Release /p:CL_MPCount=2
  mac:
    runs-on: macOS-10.14
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: macOS Xcode 10.2
      run: |
        cmake --version
        mkdir build
        cd build
        cmake ..
        make
  mac_bake:
    runs-on: macOS-10.14
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: macOS Xcode 10.2 bake
      run: |
        git clone https://github.com/SanderMertens/bake
        make -C bake/build-$(uname)
        bake/bake setup
        bake
        bake test
  win_bake:
    runs-on: windows-2016
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Windows VS2017 bake
      run: |
        git clone https://github.com/SanderMertens/bake
        cd bake
        cd build-Windows
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && nmake
        cd ..
        bake setup --local
        bake
        bake test
